title: Angelo Albiero Neto
email: blog@albiere.com
description: "Hey, I am Angelo Albiero Neto. Let's share some stuff about Software Development"
url: "http://albiere.com"

twitter_username: albiere
github_username:  albiere

markdown: kramdown
