title: Angelo Albiero Neto
email: blog@albiere.com
description: >
  Hi, I am Angelo Albiero Neto, Brazilian Software Developer currently living in Auckland - New Zealand. 
  I have a passion for building software with quality. Stop writing code like a crazy and start using your brain first.
baseurl: ""
url: "http://albiere.com"
twitter_username: albiere
github_username:  albiere

markdown: kramdown
